# Generated by Django 5.2.7 on 2025-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(db_index=True)),
                ('length', models.IntegerField(db_index=True)),
                ('has_upper', models.BooleanField(db_index=True, default=False)),
                ('has_lower', models.BooleanField(db_index=True, default=False)),
                ('has_digit', models.BooleanField(db_index=True, default=False)),
                ('has_symbol', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
